"""Add image_url to auctions

Revision ID: 28510350ec19
Revises: a6ded8fe9c56
Create Date: 2026-01-15 14:30:55.381557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28510350ec19'
down_revision = 'a6ded8fe9c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
