"""Replace password with password_hash

Revision ID: a440bacc9fc4
Revises: 28510350ec19
Create Date: 2026-01-15 15:07:34.776216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a440bacc9fc4'
down_revision = '28510350ec19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=50), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
